### ISSUE TITLE
no rending on gazebo

### ISSUE THREAD

**Issue by jwu1980** [ROBOTIS-GIT/turtlebot3_simulations#139]
I am following this instruction to run the turtlebot3 simulation.
https://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/

However, I don’t see the rending on all models (burger/waffle/waffle_pi).
Have you seen this before?
![image](https://user-images.githubusercontent.com/8375817/104295879-39f67e00-547e-11eb-989e-6f1bd25d218a.png)

O.S.: Ubuntu 20.04.
ROS: Foxy
Turtlebot3_simulation branch: tried both ros2/foxy-devel

**Comment by ROBOTIS-Will** [comment]
@jwu1980 
Hi, the rendering file used to be very large and had too much details in it.
Since simulation does not require such details, there were several requests to simplify the modeling file as much as possible.
If you need more detailed modeling files, you can find them from the previous commit below.
https://github.com/ROBOTIS-GIT/turtlebot3_simulations/tree/58b752a6ac26ae2e3be58b7b0d61af044d570c1f/turtlebot3_gazebo/models
Thank you.

**Comment by jwu1980** [comment]
Thanks Willson.
